export const mock = {
  week: {
    monday: {
      meals: [
        {
          id: 1699047,
          imageType: "jpg",
          title: "Maple Honey Zucchini Bread",
          readyInMinutes: 135,
          servings: 12,
          sourceUrl:
            "https://www.cookiemadness.net/2022/01/20/maple-honey-zucchini-bread/",
        },
        {
          id: 267661,
          imageType: "jpg",
          title: "Pesto Pasta Toss",
          readyInMinutes: 17,
          servings: 6,
          sourceUrl:
            "http://www.kraftrecipes.com/recipes/pesto-pasta-toss-55749.aspx",
        },
        {
          id: 299898,
          imageType: "jpeg",
          title: "Cornbread Stuffing",
          readyInMinutes: 80,
          servings: 8,
          sourceUrl:
            "http://www.foodnetwork.com/recipes/michael-symon/cornbread-stuffing-recipe.html",
        },
      ],
      nutrients: {
        calories: 1766.23,
        protein: 48.93,
        fat: 70.43,
        carbohydrates: 238.81,
      },
    },
    tuesday: {
      meals: [
        {
          id: 1697671,
          imageType: "jpg",
          title: "Sour Cream Coffee Cake",
          readyInMinutes: 60,
          servings: 12,
          sourceUrl: "https://spoonacular.com/sour-cream-coffee-cake-1697671",
        },
        {
          id: 406122,
          imageType: "jpg",
          title: "Garbanzo-Vegetable Green Curry",
          readyInMinutes: 20,
          servings: 6,
          sourceUrl:
            "http://www.tasteofhome.com/Recipes/garbanzo-vegetable-green-curry",
        },
        {
          id: 638263,
          imageType: "jpg",
          title: "Chicken Pita Fajita",
          readyInMinutes: 45,
          servings: 4,
          sourceUrl: "https://spoonacular.com/chicken-pita-fajita-638263",
        },
      ],
      nutrients: {
        calories: 1730.94,
        protein: 54.57,
        fat: 59.56,
        carbohydrates: 246.25,
      },
    },
    wednesday: {
      meals: [
        {
          id: 1690377,
          imageType: "jpg",
          title: "Healthy One Pan Breakfast",
          readyInMinutes: 20,
          servings: 2,
          sourceUrl: "https://hedihearts.com/healthy-one-pan-breakfast/",
        },
        {
          id: 1093320,
          imageType: "jpg",
          title: "Balsamic vinegar potatoes",
          readyInMinutes: 30,
          servings: 2,
          sourceUrl:
            "https://www.bbcgoodfood.com/recipes/711635/balsamic-vinegar-potatoes",
        },
        {
          id: 1034205,
          imageType: "jpg",
          title: "Gluten Free Waffle Cake",
          readyInMinutes: 30,
          servings: 6,
          sourceUrl:
            "https://www.thismamacooks.com/2018/08/gluten-free-waffle-cake.html",
        },
      ],
      nutrients: {
        calories: 1765.02,
        protein: 43.66,
        fat: 67.89,
        carbohydrates: 263.35,
      },
    },
    thursday: {
      meals: [
        {
          id: 1525443,
          imageType: "png",
          title: "Apple Cinnamon Granola",
          readyInMinutes: 40,
          servings: 8,
          sourceUrl: "https://www.thehealthymaven.com/apple-cinnamon-granola/",
        },
        {
          id: 224026,
          imageType: "jpg",
          title: "Home-from-work spaghetti",
          readyInMinutes: 20,
          servings: 4,
          sourceUrl:
            "https://www.bbcgoodfood.com/recipes/3286/homefromwork-spaghetti",
        },
        {
          id: 379865,
          imageType: "jpg",
          title: "Garden Pizza",
          readyInMinutes: 30,
          servings: 2,
          sourceUrl: "http://www.tasteofhome.com/Recipes/garden-pizza",
        },
      ],
      nutrients: {
        calories: 1737.53,
        protein: 56.05,
        fat: 70.96,
        carbohydrates: 223.47,
      },
    },
    friday: {
      meals: [
        {
          id: 628371,
          imageType: "jpg",
          title: "Apricot Cherry Breakfast Bread",
          readyInMinutes: 45,
          servings: 8,
          sourceUrl:
            "http://www.barbarabakes.com/2015/02/apricot-cherry-breakfast-bread/",
        },
        {
          id: 602408,
          imageType: "jpg",
          title: "Pasta with Cajun Cream Sauce",
          readyInMinutes: 15,
          servings: 4,
          sourceUrl:
            "http://www.steamykitchen.com/73-pasta-with-creamy-cajun-sauce.html",
        },
        {
          id: 282804,
          imageType: "jpg",
          title: "Caribbean Shrimp",
          readyInMinutes: 20,
          servings: 6,
          sourceUrl:
            "http://www.kraftrecipes.com/recipes/caribbean-shrimp-54305.aspx",
        },
      ],
      nutrients: {
        calories: 1776.53,
        protein: 55.41,
        fat: 69.42,
        carbohydrates: 244.88,
      },
    },
    saturday: {
      meals: [
        {
          id: 1665071,
          imageType: "jpg",
          title: "Bibingka Waffles",
          readyInMinutes: 45,
          servings: 6,
          sourceUrl: "https://www.bonappetit.com/recipe/bibingka-waffles",
        },
        {
          id: 1089525,
          imageType: "jpg",
          title: "Spiced halloumi & pineapple burger with zingy slaw",
          readyInMinutes: 25,
          servings: 2,
          sourceUrl:
            "https://www.bbcgoodfood.com/recipes/spiced-halloumi-pineapple-burger-zingy-slaw",
        },
        {
          id: 299898,
          imageType: "jpeg",
          title: "Cornbread Stuffing",
          readyInMinutes: 80,
          servings: 8,
          sourceUrl:
            "http://www.foodnetwork.com/recipes/michael-symon/cornbread-stuffing-recipe.html",
        },
      ],
      nutrients: {
        calories: 1761.52,
        protein: 44.4,
        fat: 74.05,
        carbohydrates: 240.62,
      },
    },
    sunday: {
      meals: [
        {
          id: 640965,
          imageType: "jpg",
          title: "Crushed Lentil Soup- Granola Style",
          readyInMinutes: 45,
          servings: 1,
          sourceUrl:
            "https://spoonacular.com/crushed-lentil-soup-granola-style-640965",
        },
        {
          id: 28320,
          imageType: "jpg",
          title: "Zucchini Linguine with Herbs",
          readyInMinutes: 30,
          servings: 8,
          sourceUrl:
            "http://www.foodandwine.com/recipes/zucchini-linguine-with-herbs",
        },
        {
          id: 1070648,
          imageType: "jpg",
          title: "Easy Tomato Basil Chicken – One Pot Meal",
          readyInMinutes: 30,
          servings: 6,
          sourceUrl:
            "https://spoonacular.com/easy-tomato-basil-chicken-one-pot-meal-1070648",
        },
      ],
      nutrients: {
        calories: 1787.39,
        protein: 51.37,
        fat: 67.74,
        carbohydrates: 244.72,
      },
    },
  },
};

export const formMock = [
  {
    Gender: "Male(ชาย)",
    Age: 20,
    Weight: 50,
    Height: 170,
    Exercise: 0,
    FastFood: 1,
    Favourite: "Pizza",
    Breakfast: "Basil with Rice(ข้าวกะเพรา)",
    Lunch: "Pork Knuckle Rice(ข้าวขาหมู)",
    Dinner: "pizza(พิซซ่า)",
    Calculate: "No",
  },
  {
    Gender: "Female(หญิง)",
    Age: 20,
    Weight: 45,
    Height: 167,
    Exercise: 1,
    FastFood: 2,
    Favourite: "Fried Chicken",
    Breakfast: "rice porridge(โจ๊ก)",
    Lunch: "Basil with Rice(ข้าวกะเพรา)",
    Dinner: "Pork Knuckle Rice(ข้าวขาหมู)",
    Calculate: "No",
  },
  {
    Gender: "Male(ชาย)",
    Age: 21,
    Weight: 55,
    Height: 167,
    Exercise: 3,
    FastFood: 1,
    Favourite: "Spaghetti",
    Breakfast: "Fried Chicken with Sticky Rice(ไก่ทอดกับข้าวเหนียว)",
    Lunch: "noodles(ก๋วยเตี๋ยว)",
    Dinner: "Salad(สลัด)",
    Calculate: "Yes",
  },
  {
    Gender: "Male(ชาย)",
    Age: 23,
    Weight: 40,
    Height: 167,
    Exercise: 0,
    FastFood: 1,
    Favourite: "Burger",
    Breakfast: "Grilled Pork with Sticky Rice(หมูปิ้งกับข้าวเหนียว)",
    Lunch: "Crispy egg noodles with Chinese broccoli (ราดหน้าหมี่กรอบ หมูหมัก)",
    Dinner: "noodles(ก๋วยเตี๋ยว)",
    Calculate: "No",
  },
  {
    Gender: "Female(หญิง)",
    Age: 19,
    Weight: 50,
    Height: 165,
    Exercise: 0,
    FastFood: 3,
    Favourite: "Fried Chicken",
    Breakfast: "noodles(ก๋วยเตี๋ยว)",
    Lunch: "Spaghetti(สปาเก็ตตี้)",
    Dinner: "Crispy Pork with Rice(ข้าวหมูกรอบ)",
    Calculate: "No",
  },
  {
    Gender: "Male(ชาย)",
    Age: 22,
    Weight: 60,
    Height: 180,
    Exercise: 5,
    FastFood: 2,
    Favourite: "Pizza",
    Breakfast: "rice porridge(โจ๊ก)",
    Lunch: "Basil with Rice(ข้าวกะเพรา)",
    Dinner: "Salad(สลัด)",
    Calculate: "Yes",
  },
  {
    Gender: "Female(หญิง)",
    Age: 25,
    Weight: 43,
    Height: 170,
    Exercise: 0,
    FastFood: 2,
    Favourite: "Spaghetti",
    Breakfast: "Grilled Pork with Sticky Rice(หมูปิ้งกับข้าวเหนียว)",
    Lunch: "noodles(ก๋วยเตี๋ยว)",
    Dinner: "Salad(สลัด)",
    Calculate: "Yes",
  },
  {
    Gender: "Female(หญิง)",
    Age: 22,
    Weight: 46,
    Height: 173,
    Exercise: 2,
    FastFood: 1,
    Favourite: "Pizza",
    Breakfast: "Fried Chicken with Sticky Rice(ไก่ทอดกับข้าวเหนียว)",
    Lunch: "Crispy Pork with Rice(ข้าวหมูกรอบ)",
    Dinner: "Basil with Rice(ข้าวกะเพรา)",
    Calculate: "No",
  },
  {
    Gender: "Male(ชาย)",
    Age: 20,
    Weight: 46,
    Height: 169,
    Exercise: 0,
    FastFood: 4,
    Favourite: "Burger",
    Breakfast: "Basil with Rice(ข้าวกะเพรา)",
    Lunch: "Crispy egg noodles with Chinese broccoli (ราดหน้าหมี่กรอบ หมูหมัก)",
    Dinner: "Spaghetti(สปาเก็ตตี้)",
    Calculate: "No",
  },
  {
    Gender: "Female(หญิง)",
    Age: 24,
    Weight: 52,
    Height: 170,
    Exercise: 0,
    FastFood: 2,
    Favourite: "Spaghetti",
    Breakfast: "rice porridge(โจ๊ก)",
    Lunch: "pizza(พิซซ่า)",
    Dinner: "Burger(เบอร์เกอร์)",
    Calculate: "No",
  },
  {
    Gender: "Male(ชาย)",
    Age: 21,
    Weight: 43,
    Height: 165,
    Exercise: 0,
    FastFood: 4,
    Favourite: "Fried Chicken",
    Breakfast: "Salad(สลัด)",
    Lunch: "Crispy Pork with Rice(ข้าวหมูกรอบ)",
    Dinner: "pizza(พิซซ่า)",
    Calculate: "No",
  },
  {
    Gender: "Male(ชาย)",
    Age: 21,
    Weight: 55,
    Height: 170,
    Exercise: 2,
    FastFood: 1,
    Favourite: "Pizza",
    Breakfast: "rice porridge(โจ๊ก)",
    Lunch: "Spaghetti(สปาเก็ตตี้)",
    Dinner: "Grilled Pork with Sticky Rice(หมูปิ้งกับข้าวเหนียว)",
    Calculate: "No",
  },
  {
    Gender: "Male(ชาย)",
    Age: 21,
    Weight: 47,
    Height: 168,
    Exercise: 6,
    FastFood: 0,
    Favourite: "Fried Chicken",
    Breakfast: "rice porridge(โจ๊ก)",
    Lunch: "Salad(สลัด)",
    Dinner: "Basil with Rice(ข้าวกะเพรา)",
    Calculate: "Yes",
  },
  {
    Gender: "Male(ชาย)",
    Age: 22,
    Weight: 46,
    Height: 175,
    Exercise: 0,
    FastFood: 2,
    Favourite: "Spaghetti",
    Breakfast: "Fried Chicken with Sticky Rice(ไก่ทอดกับข้าวเหนียว)",
    Lunch: "Crispy Pork with Rice(ข้าวหมูกรอบ)",
    Dinner:
      "Crispy egg noodles with Chinese broccoli (ราดหน้าหมี่กรอบ หมูหมัก)",
    Calculate: "No",
  },
  {
    Gender: "Male(ชาย)",
    Age: 21,
    Weight: 65,
    Height: 173,
    Exercise: 0,
    FastFood: 3,
    Favourite: "Pizza",
    Breakfast: "Crispy Pork with Rice(ข้าวหมูกรอบ)",
    Lunch: "Crispy egg noodles with Chinese broccoli (ราดหน้าหมี่กรอบ หมูหมัก)",
    Dinner: "Burger(เบอร์เกอร์)",
    Calculate: "No",
  },
  {
    Gender: "Male(ชาย)",
    Age: 20,
    Weight: 43,
    Height: 166,
    Exercise: 0,
    FastFood: 1,
    Favourite: "Spaghetti",
    Breakfast: "Grilled Pork with Sticky Rice(หมูปิ้งกับข้าวเหนียว)",
    Lunch: "noodles(ก๋วยเตี๋ยว)",
    Dinner: "Basil with Rice(ข้าวกะเพรา)",
    Calculate: "No",
  },
  {
    Gender: "Male(ชาย)",
    Age: 19,
    Weight: 50,
    Height: 170,
    Exercise: 0,
    FastFood: 2,
    Favourite: "Fried Chicken",
    Breakfast: "noodles(ก๋วยเตี๋ยว)",
    Lunch: "Basil with Rice(ข้าวกะเพรา)",
    Dinner: "Burger(เบอร์เกอร์)",
    Calculate: "No",
  },
  {
    Gender: "Male(ชาย)",
    Age: 23,
    Weight: 54,
    Height: 165,
    Exercise: 4,
    FastFood: 4,
    Favourite: "Pizza",
    Breakfast: "rice porridge(โจ๊ก)",
    Lunch: "Pork Knuckle Rice(ข้าวขาหมู)",
    Dinner:
      "Crispy egg noodles with Chinese broccoli (ราดหน้าหมี่กรอบ หมูหมัก)",
    Calculate: "Yes",
  },
  {
    Gender: "Female(หญิง)",
    Age: 20,
    Weight: 50,
    Height: 164,
    Exercise: 1,
    FastFood: 6,
    Favourite: "Spaghetti",
    Breakfast: "rice porridge(โจ๊ก)",
    Lunch: "Basil with Rice(ข้าวกะเพรา)",
    Dinner: "Salad(สลัด)",
    Calculate: "Yes",
  },
  {
    Gender: "Male(ชาย)",
    Age: 21,
    Weight: 40,
    Height: 171,
    Exercise: 7,
    FastFood: 2,
    Favourite: "Fried Chicken",
    Breakfast: "rice porridge(โจ๊ก)",
    Lunch: "Basil with Rice(ข้าวกะเพรา)",
    Dinner: "Salad(สลัด)",
    Calculate: "Yes",
  },
];

export const caloriesMock = [
  {
    age: 18,
    calorie: 1600,
  },
  {
    age: 20,
    calorie: 1800
  }
];

export const genderMock = [
    {
        gender: "Male",
        calorie: 2000
    },
    {
        gender: "Female",
        calorie: 1500
    }
]
